name: ai_video_generator
description: AI-powered video generation system with Flutter frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  file_picker: ^6.1.1
  video_player: ^2.7.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  video_thumbnail: ^0.5.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/ 