version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./media_assets:/app/media_assets
      - ./output:/app/output
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_VISION_KEY=${AZURE_VISION_KEY}
      - AZURE_VISION_ENDPOINT=${AZURE_VISION_ENDPOINT}
      - RUNWAYML_API_KEY=${RUNWAYML_API_KEY}
      - PIKALABS_API_KEY=${PIKALABS_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - FLUTTER_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped 